baseurl = "http://press.mcfog.wang/"
languageCode = "zh-cn"
title = "McFog＠がんばらない"

theme = "mcpress"
copyright = "2020 McFog W. All rights reserved."

[permalinks]
  post = "/:year/:month/:slug/"

[markup]
  [markup.highlight]
    guessSyntax = true
    style = "github"
